# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'LogSampleProject' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for LogSampleProject
  pod 'CocoaLumberjack'
  pod 'AFNetworking', '~> 3.1.0'
end
